In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import joblib

In [3]:
n = 500
area = np.random.randint(600,3500,size=n)
bedroom = np.random.randint(1,6,size=n)
price_lakhs = .035*area + .5*bedroom + np.random.randint(10,50,size=n)

In [4]:
df = pd.DataFrame({ 'area': area, 'bedroom': bedroom, 'price_lakhs': price_lakhs })

In [6]:
df.head()

   area  bedroom  price_lakhs
0  2157        1      116.995
1  2893        2      142.255
2   686        4       73.010
3  1795        5       81.325
4  2874        4      145.590

In [7]:
x = df[['area','bedroom']]
y = df['price_lakhs']

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [9]:
x_train

     area  bedroom
249   640        1
433  1803        4
19   2529        1
322  1892        5
332  1244        5
..    ...      ...
106  3153        2
270  2708        1
348  2190        3
435  1745        1
102  2081        5

[400 rows x 2 columns]

In [10]:
y_train

249     63.900
433    106.105
19     100.015
322     90.720
332     88.040
        ...
106    151.355
270    126.280
348     91.150
435     86.575
102     90.335
Name: price_lakhs, Length: 400, dtype: float64

In [11]:
x_test

     area  bedroom
361  3217        5
73   3103        4
374  3189        1
155   731        5
104  2717        1
..    ...      ...
347  1054        3
86   1614        5
75   2421        2
438  2342        1
15   2035        4

[100 rows x 2 columns]

In [12]:
y_test

361    133.095
73     156.605
374    134.115
155     43.085
104    133.595
        ...
347     64.390
86      69.990
75     121.735
438     98.470
15     120.225
Name: price_lakhs, Length: 100, dtype: float64

In [13]:
model = LinearRegression()

In [15]:
model.fit(x_train, y_train)

LinearRegression()

In [16]:
model.intercept_

np.float64(29.37453605597858)

In [17]:
model.coef_

array([0.03465226, 0.73824491])

In [19]:
model.predict([[6500,3]])

d:\finetuning\fullfinetuning\.conda\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([256.82899097])

In [20]:
r2_score(y_test, model.predict(x_test))

0.86020646804352

In [21]:
joblib.dump(model, 'linear_regression_model.pkl')

['linear_regression_model.pkl']